### ISSUE TITLE
404 When deploying to live Apache

### ISSUE THREAD

**Issue by hanto899** [amercier/generator-angular-php#7]
I keep receiving a 404 when application is trying to do the initial (and all) GET requests for /api/features

This is after a build the application with grunt, copied the files and folders from the dist-folder to my /public_html/ on my apache server

I added it to stackoverflow, here is the link to that question: http://stackoverflow.com/questions/27472545/angularjs-slim-404-not-found-for-get-request

I am guessing that nothing is really wrong with generator-angular-php but rather my apache/.htaccess settings that are causing this. But i thought, someone might have run into the same problem here, and perhaps, can shed some light on why it isn't working.

BR,
hanto899

**Comment by swordf1zh** [comment]
@hanto899 @amercier I'm still having the same issue in v0.6.2..
